# Generated by Django 5.0.4 on 2024-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cymbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('size', models.IntegerField(max_length=2)),
                ('brand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=256)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
