# Generated by Django 5.0.4 on 2024-04-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cymbal_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Hire Date')),
                ('event', models.CharField(choices=[('C', 'Clinic'), ('R', 'Recording'), ('G', 'Gig')], default='C', max_length=1)),
                ('cymbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cymbal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
