# Generated by Django 5.0.4 on 2024-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cymbal_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='cymbal',
            name='favoriteOf',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
