# Generated by Django 5.0.4 on 2024-04-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cymbal_favoriteof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('band', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='cymbal',
            name='artist',
            field=models.ManyToManyField(to='main_app.artist'),
        ),
    ]
